[[language]]
name = "rust"
formatter = { command = "rustfmt" }

[[language]]
name = "markdown"
soft-wrap.enable = true

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }

[language-server.taplo]
config = {}
